# Generated by Django 5.1.1 on 2024-09-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loginmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Emailaddress', models.CharField(max_length=100)),
                ('Password', models.IntegerField()),
                ('Againpassword', models.IntegerField()),
            ],
        ),
    ]
